#!/usr/bin/env bash

phpunit --verbose --bootstrap src/replayer-tests/bootstrap.php src/replayer-tests/
#phpunit --filter test_invalidstreamid_using_get --verbose --bootstrap src/replayer-tests/bootstrap.php src/replayer-tests/getters/SimpleGetTest.php
